export { Home } from './home'
export { ChildrenStudio } from './children-studio'
export { Plays } from './plays'
export { Play } from './play'
export { RomashkaAwards } from './romashka-awards'
export { Press } from './press'
export { Contacts } from './contacts'
export { Scenes } from './scenes'
